FROM balenalib/%%BALENA_MACHINE_NAME%%-golang:latest-build AS build
COPY . ./

RUN go build

FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:stretch

WORKDIR /go/src/github.com/balena-io-projects/app
COPY --from=build /go/src/github.com/balena-io-projects/app/ .
RUN pwd
RUN ls -l
CMD ./app

# FROM alpine:latest
# RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
# COPY arduino-wx-go-logger /arduino-wx-go-logger
# CMD ["/arduino-wx-go-logger"]
